export const CUISINE_TYPES = [
  "Española",
  "Italiana",
  "Mexicana",
  "Japonesa",
  "Tapas",
  "Mediterránea",
  "Francesa",
  "China",
  "India",
  "Tailandesa",
  "Coreana",
  "Peruana",
  "Argentina",
  "Libanesa",
  "Griega",
  "Americana",
  "Venezolana",
  "Brasileña",
  "Turca",
  "Marroquí",
  "Vietnamita",
  "Fusión",
  "Hamburguesas",
  "Pizza",
  "Sushi",
  "Ramen",
  "Tacos",
  "Bocadillos / Sandwiches",
  "Carne",
  "Parrilla / Barbacoa",
  "Pescado",
  "Marisco",
  "Arroces",
  "Pasta",
  "Ensaladas / Healthy",
  "Vegetariana",
  "Vegana",
  "Sin gluten",
  "Brunch",
  "Desayunos",
  "Café",
  "Pastelería / Dulces",
  "Heladería",
  "Bar / Copas",
  "Coctelería",
  "Vinos",
  "Comida rápida",
  "Street food",
  "Buffet",
  "Menú del día",
  "Alta cocina",
  "Tradicional / Casera",
  "Otra",
];

export const OCCASION_TYPES = [
  "Amigos",
  "Familia",
  "Cita",
  "Trabajo",
  "Rápido / informal",
  "Celebración",
  "Cumpleaños",
  "Aniversario",
  "Cena especial",
  "Comida de diario",
  "Comida rápida",
  "Plan tranquilo",
  "Plan elegante",
  "Plan barato",
  "Plan caro / lujo",
  "Terraza",
  "Copas",
  "Brunch",
  "Desayuno",
  "Merienda",
  "Tardeo",
  "Afterwork",
  "Primera cita",
  "Pareja",
  "Grupo grande",
  "Solo",
  "Niños / familiar",
  "Reunión informal",
  "Reunión de empresa",
  "Turismo / viaje",
  "Ver partido",
  "Música / ambiente",
  "Sitio romántico",
  "Sitio tranquilo",
  "Sitio animado",
  "Para compartir platos",
  "Para probar algo nuevo",
  "Para repetir",
  "Para impresionar",
  "Para llevar",
  "Delivery",
  "Otra",
];

export const PRICE_RANGES = [
  "0-10 €",
  "10-20 €",
  "20-30 €",
  "30-40 €",
  "40-50 €",
  "50-60 €",
  "60-70 €",
  "70-80 €",
  "80-90 €",
  "90-100 €",
  "+100 €",
];
