export const CUISINE_TYPES = [
  "Española",
  "Mediterránea",
  "Italiana",
  "Francesa",
  "Mexicana",
  "Peruana",
  "Argentina",
  "Colombiana",
  "Venezolana",
  "Brasileña",
  "Japonesa",
  "China",
  "Coreana",
  "Tailandesa",
  "India",
  "Vietnamita",
  "Libanesa",
  "Marroquí",
  "Griega",
  "Turca",
  "Americana",
  "Tex-Mex",
  "Fusión",
  "Internacional",
  "Vegetariana",
  "Vegana",
  "Saludable / healthy",
  "Mariscos / pescados",
  "Carnes / steakhouse",
  "Hamburguesas",
  "Pizza",
  "Pasta",
  "Sushi",
  "Tapas / raciones",
  "Bocadillos / sandwiches",
  "Brunch",
  "Desayunos",
  "Repostería / pastelería",
  "Cafetería",
  "Comida rápida",
  "Comida callejera / street food",
  "Gourmet / alta cocina",
  "Cocina de autor",
  "Cocina tradicional",
  "Cocina casera",
];

export const OCCASION_TYPES = [
  "Comida diaria",
  "Cena informal",
  "Cena romántica",
  "Primera cita",
  "Comida de trabajo",
  "Cena de empresa",
  "Reunión con amigos",
  "Celebración familiar",
  "Cumpleaños",
  "Aniversario",
  "Pedida / compromiso",
  "Celebración especial",
  "Comida rápida",
  "Para llevar",
  "Delivery",
  "Brunch de fin de semana",
  "Desayuno tranquilo",
  "Merienda",
  "Afterwork",
  "Copas / cócteles",
  "Tapas con amigos",
  "Cena elegante",
  "Alta cocina / experiencia gastronómica",
  "Plan con niños",
  "Plan familiar",
  "Grupo grande",
  "Cena íntima",
  "Turismo / probar comida local",
  "Ocasión económica",
  "Ocasión premium",
  "Comer solo",
  "Reunión casual",
  "Celebración de graduación",
  "Comida saludable",
  "Comida antes o después de un evento",
  "Plan de domingo",
  "Cena tardía",
];

export const PRICE_RANGES = [
  "0-10 €",
  "10-20 €",
  "20-30 €",
  "30-40 €",
  "40-50 €",
  "50-60 €",
  "60-70 €",
  "70-80 €",
  "80-90 €",
  "90-100 €",
  "+100 €",
];
